# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIStudy
  pod 'SwiftLint'

  target 'SwiftUIStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIStudyUITests' do
    # Pods for testing
  end

end
