name: Swift

on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'SwiftUIStudy', destination: 'platform=iOS Simulator,OS=14.4,name=iPhone 8' }
          - { scheme: 'SwiftUIStudy', destination: 'platform=iOS Simulator,OS=14.4,name=iPhone 11' }
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p
    - name: Show Build Settings
      run: xcodebuild -workspace SwiftUIStudy/SwiftUIStudy.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings
    - name: Show Build SDK
      run: xcodebuild -workspace SwiftUIStudy/SwiftUIStudy.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showsdks
    - name: Show Available Destinations
      run: xcodebuild -workspace SwiftUIStudy/SwiftUIStudy.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations
    - name: lint
      run: swiftlint SwiftUIStudy/ 
    - name: build and test
      run: xcodebuild clean test -workspace SwiftUIStudy/SwiftUIStudy.xcworkspace -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
